# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Remove Java JDK 11
        run: sudo apt-get remove --auto-remove openjdk*

      - name: Setup Java JDK 16
        uses: actions/setup-java@v2.1.0
        with:
          java-version: '16'
          distribution: 'adopt'
          java-package: 'jdk'
          architecture: 'x64'

      - name: Check Java version
        run: java -version

      - name: Config
        run: chmod +x ./gradlew

      - name: Run gradlew
        run: ./gradlew

      - name: Run build
        run: ./gradlew jar
