# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master, actions ]
  pull_request:
    branches: [ master, actions ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt-openj9'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Clean Build
      run: ./gradlew clean build
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2.2.4
      with:
        name: EcoEnchants Artifacts
        path: ./bin/*.jar
